baseurl = "/"
languageCode = "en-us"
title = "Jett's DevBlog"
theme = "hyde"

# Pagination
paginate = 5
paginatePath = "page"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Jett Durham"
    email = "jett@jettdurham.com"

[params]
themeColor = "theme-base-0d"
  intro = true
  headline = "Jett's DevBlog"
  description = "Musings on Software Development"
  github = "https://github.com/thejettdurham"
  linkedin = "https://linkedin.com/in/thejettdurham/"
  twitter = "https://twitter.com/thejettdurham"
  facebook = "https://facebook.com/thejettdurham"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
