baseurl = "/"
languageCode = "en-us"
title = "Jett's DevBlog"
theme = "hyde"

# Pagination
paginate = 5
paginatePath = "page"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Jett Durham"
    email = "jett@jettdurham.com"

[params]
  themeColor = "theme-base-0d"
  intro = true
  headline = "Jett's DevBlog"
  description = "How I Build Things With Small Teams"
  github = "thejettdurham"
  linkedin = "thejettdurham"
  twitter = "thejettdurham"
  youtube = "UC1PJB2gUdwtQUMMsLxDPAgw"

[params.sidebar]
  logo = "images/shot-cropped-web.jpg"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
